Feature user can create deck
arjunkahlon/deck-study pull request #10
Opened 2022-09-13 01:03 UTC by arjunkahlon

![Screen Shot 2022-09-12 at 3 57 02 PM](https://user-images.githubusercontent.com/49361894/189784845-5f750c68-e2f6-4e93-a6d5-f07cb73171e0.png)
<img width="1434" alt="Screen Shot 2022-09-12 at 6 02 54 PM" src="https://user-images.githubusercontent.com/49361894/189784848-61105fb7-6740-4d0b-872f-f9fffd1aa6d4.png">

2022-09-13 01:04 UTC, arjunkahlon commented
<img width="1113" alt="Screen Shot 2022-09-12 at 6 03 50 PM" src="https://user-images.githubusercontent.com/49361894/189784911-bcbed5aa-78be-43f7-a003-b86d7e83d97c.png">

2022-09-13 01:13 UTC, thebearingedge requested changes
Please include your modal form for allowing the user to name the new deck

<img width="441" alt="image" src="https://user-images.githubusercontent.com/7432943/189785715-4b09512b-30ee-41e4-845c-3dc1da5cba3b.png">

2022-09-13 23:51 UTC, arjunkahlon commented
![add-deck-component](https://user-images.githubusercontent.com/49361894/190029109-1b834b14-e7dc-4892-a3f0-e9a088bbdb6d.gif)
![Screen Shot 2022-09-13 at 4 48 07 PM](https://user-images.githubusercontent.com/49361894/190029140-bc8b072f-0277-4dc6-a11b-3a0bb133df1e.png)

2022-09-13 23:54 UTC, thebearingedge requested changes
Ok, great! Just a little cleanup

2022-09-13 23:54 UTC, thebearingedge commented on server/index.js
> +
Please remove this so we don't accidentally introduce unnecessary variables.

2022-09-13 23:54 UTC, thebearingedge commented on server/public/layout.css
> +}
There are a few Bootstrap helper classes you can use to replace all of these.

2022-09-13 23:54 UTC, thebearingedge commented on client/app.jsx
> +// import AppContext from './lib/app-context';
Please remove commented out lines

2022-09-14 00:02 UTC, thebearingedge approved these changes

2022-09-14 00:03 UTC, merged